'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Copy, Download, Check, ChevronDown, ChevronRight, Bookmark } from 'lucide-react';
import { jsPDF } from 'jspdf';

export default function NotesDisplay({ notes, videoTitle, videoUrl }) {
  const [copied, setCopied] = useState(false);
  const [collapsedSections, setCollapsedSections] = useState({});

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(notes);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      // Fallback
      const textarea = document.createElement('textarea');
      textarea.value = notes;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(59, 130, 246);
    const titleLines = doc.splitTextToSize(videoTitle || 'InferaNotes', maxWidth);
    doc.text(titleLines, margin, y);
    y += titleLines.length * 8 + 5;

    // Separator
    doc.setDrawColor(59, 130, 246);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Content
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);

    const lines = notes.split('\n');
    lines.forEach((line) => {
      if (y > 280) {
        doc.addPage();
        y = 20;
      }

      if (line.startsWith('## ')) {
        y += 5;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(13);
        doc.setTextColor(59, 130, 246);
        const text = line.replace('## ', '');
        const splitText = doc.splitTextToSize(text, maxWidth);
        doc.text(splitText, margin, y);
        y += splitText.length * 6 + 3;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(30, 41, 59);
      } else if (line.startsWith('### ')) {
        y += 3;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(71, 85, 105);
        const text = line.replace('### ', '');
        const splitText = doc.splitTextToSize(text, maxWidth);
        doc.text(splitText, margin, y);
        y += splitText.length * 5 + 2;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(30, 41, 59);
      } else if (line.startsWith('- ')) {
        const text = '  • ' + line.replace(/^- \*\*(.+?)\*\*:?/, '$1:').replace(/\*\*/g, '');
        const splitText = doc.splitTextToSize(text, maxWidth - 5);
        doc.text(splitText, margin + 3, y);
        y += splitText.length * 5;
      } else if (line.trim()) {
        const cleanLine = line.replace(/\*\*/g, '').replace(/\*/g, '');
        const splitText = doc.splitTextToSize(cleanLine, maxWidth);
        doc.text(splitText, margin, y);
        y += splitText.length * 5;
      } else {
        y += 3;
      }
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by InferaNotes — inferanotes.vercel.app', margin, 290);

    doc.save(`${(videoTitle || 'notes').replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
  };

  const toggleSection = (key) => {
    setCollapsedSections((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  // Parse markdown notes into sections
  const renderNotes = () => {
    if (!notes) return null;

    const lines = notes.split('\n');
    const sections = [];
    let currentSection = null;
    let sectionIndex = 0;

    lines.forEach((line, i) => {
      if (line.startsWith('## ')) {
        if (currentSection) sections.push(currentSection);
        sectionIndex++;
        currentSection = {
          key: `section-${sectionIndex}`,
          title: line.replace('## ', ''),
          content: [],
          type: 'h2',
        };
      } else if (line.startsWith('# ') && !line.startsWith('## ')) {
        if (currentSection) sections.push(currentSection);
        currentSection = {
          key: `title-${i}`,
          title: line.replace('# ', ''),
          content: [],
          type: 'h1',
        };
      } else if (currentSection) {
        currentSection.content.push(line);
      } else {
        if (!currentSection) {
          currentSection = {
            key: `intro-${i}`,
            title: '',
            content: [line],
            type: 'intro',
          };
        }
      }
    });
    if (currentSection) sections.push(currentSection);

    return sections.map((section) => {
      if (section.type === 'h1') {
        return (
          <h1 key={section.key} className="text-2xl font-bold mb-4 gradient-text">
            {section.title}
          </h1>
        );
      }

      const isCollapsed = collapsedSections[section.key];
      const isKeySection =
        section.title.toLowerCase().includes('key') ||
        section.title.toLowerCase().includes('summary') ||
        section.title.toLowerCase().includes('review');

      return (
        <div key={section.key} className="mb-6">
          {section.title && (
            <button
              onClick={() => toggleSection(section.key)}
              className="flex items-center gap-2 w-full text-left mb-3 group cursor-pointer"
            >
              <motion.span
                animate={{ rotate: isCollapsed ? 0 : 90 }}
                transition={{ duration: 0.2 }}
              >
                <ChevronRight size={18} className="text-blue-400" />
              </motion.span>
              <h2 className="text-xl font-semibold gradient-text flex items-center gap-2">
                {section.title}
                {isKeySection && <Bookmark size={16} className="text-yellow-400" />}
              </h2>
            </button>
          )}

          <AnimatePresence>
            {!isCollapsed && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.3 }}
                className="overflow-hidden"
              >
                <div
                  className={`pl-6 ${isKeySection ? 'key-concept' : ''}`}
                >
                  {section.content.map((line, j) => {
                    if (line.startsWith('### ')) {
                      return (
                        <h3 key={j} className="text-lg font-semibold mt-4 mb-2">
                          {line.replace('### ', '')}
                        </h3>
                      );
                    }
                    if (line.startsWith('- ')) {
                      const content = line.replace('- ', '');
                      return (
                        <div key={j} className="flex items-start gap-2 py-1 group/item">
                          <span className="text-blue-400 mt-1 shrink-0">▸</span>
                          <span
                            className="text-sm leading-relaxed transition-colors group-hover/item:text-blue-200"
                            style={{ color: 'var(--muted)' }}
                            dangerouslySetInnerHTML={{
                              __html: content
                                .replace(
                                  /\*\*(.+?)\*\*/g,
                                  '<strong style="color: #60A5FA">$1</strong>'
                                )
                                .replace(
                                  /\[(\d{1,2}:\d{2})\]/g,
                                  '<span style="color: #06B6D4; cursor: pointer; text-decoration: underline">[$1]</span>'
                                ),
                            }}
                          />
                        </div>
                      );
                    }
                    if (line.match(/^\d+\.\s/)) {
                      return (
                        <div key={j} className="flex items-start gap-2 py-1">
                          <span className="text-blue-400 font-semibold shrink-0">
                            {line.match(/^(\d+)/)[1]}.
                          </span>
                          <span
                            className="text-sm leading-relaxed"
                            style={{ color: 'var(--muted)' }}
                            dangerouslySetInnerHTML={{
                              __html: line
                                .replace(/^\d+\.\s/, '')
                                .replace(
                                  /\*\*(.+?)\*\*/g,
                                  '<strong style="color: #60A5FA">$1</strong>'
                                ),
                            }}
                          />
                        </div>
                      );
                    }
                    if (line.trim() === '') return <div key={j} className="h-2" />;
                    return (
                      <p
                        key={j}
                        className="text-sm leading-relaxed py-1"
                        style={{ color: 'var(--muted)' }}
                        dangerouslySetInnerHTML={{
                          __html: line.replace(
                            /\*\*(.+?)\*\*/g,
                            '<strong style="color: #60A5FA">$1</strong>'
                          ),
                        }}
                      />
                    );
                  })}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      );
    });
  };

  return (
    <div>
      {/* Action bar */}
      <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
        <div>
          <h2 className="text-lg font-semibold">{videoTitle || 'Generated Notes'}</h2>
          {videoUrl && (
            <a
              href={videoUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-blue-400 hover:underline"
            >
              View original video →
            </a>
          )}
        </div>
        <div className="flex gap-2">
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium transition-all cursor-pointer"
            style={{
              background: copied ? 'rgba(16, 185, 129, 0.1)' : 'var(--surface)',
              border: `1px solid ${copied ? 'rgba(16, 185, 129, 0.3)' : 'var(--border-color)'}`,
              color: copied ? '#10B981' : 'var(--foreground)',
            }}
            id="copy-notes-btn"
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </motion.button>

          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleDownloadPDF}
            className="btn-primary text-sm cursor-pointer"
            id="download-pdf-btn"
          >
            <Download size={16} />
            <span>Download PDF</span>
          </motion.button>
        </div>
      </div>

      {/* Notes content */}
      <div className="notes-content">{renderNotes()}</div>
    </div>
  );
}
